config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :races, only: [:index] do
    member do
      get '/coordinates', to: "races#coordinates"
    end

    resources :boats, only: %i[new create]
  end

  resources :games, only: [:new, :show]

  resources :boats, only: %i[update] do
    member do
      get "/move", to: "games#move"
    end
  end

  get "/boat_select", to: "boats#select"

  devise_for :users

  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/boat.rb
class Boat < ApplicationRecord
  belongs_to :game

  def self.image_urls(color)
    {
      "Poppy" => "https://res.cloudinary.com/dwclozjta/image/upload/v1678372133/bateau_poppy_kqqsnl.png",
      "Navy" => "https://res.cloudinary.com/dwclozjta/image/upload/v1678372133/bateau_navy_mh1k4a.png",
      "Lemon" => "https://res.cloudinary.com/dwclozjta/image/upload/v1678372133/bateau_lemon_op5dfw.png"
    }[color]
  end
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :race
  has_many :boats, dependent: :destroy
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :games, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :boats
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController

  def new
    @boat = Boat.new
    @race = Race.find(params[:race_id])
  end

  def create
    @game = Game.new
    @game.race_id = params[:race_id]
    @boat = Boat.new(boat_params)
    @boat.game = @game
    @boat.latitude = Race.find(params[:race_id]).starting_latitude
    @boat.longitude = Race.find(params[:race_id]).starting_longitude

    if @boat.save!
      redirect_to game_path @game, params: { boat_id: @boat.id }
    else
      render :new, status: :unprocessable_entity
    end
  end

  # def edit
  #   @boat = Boat.find(params:id)
  # end

  def update
    @boat = Boat.find(params[:id])
    @boat.update(direction: params[:boat][:direction])
    ComputePositionJob.perform_later(params[:id])
    render json: { status: :ok, new_direction: @boat.direction }
  end

  def select
    render json: { url: Boat.image_urls(params[:color]) }
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :navy, :leafy, :poppy)
  end

end

app/controllers/games_controller.rb
require "open-uri"
require 'json'

class GamesController < ApplicationController
  def new
    @game = Game.new
  end

  def create
  end

  def show
    @boat = Boat.find(params[:boat_id])
    fetch_weather_data
  end

  private

  def fetch_weather_data
    uri = "https://api.aerisapi.com//conditions/closest?p=#{@boat.latitude},#{@boat.longitude}&client_id=#{ENV["CLIENT_ID"]}&client_secret=#{ENV["CLIENT_SECRET"]}"
    payload = URI.open(uri).read
    data = JSON.parse(payload)
    @image_url = data['response']&.first['periods']&.first['icon']
    @wind_speedy = data['response']&.first['periods']&.first['windSpeedMPH']
    @wind_direction = data['response']&.first['periods']&.first['windDirDEG']
    @weather = data['response']&.first['periods']&.first['weather']
    @tempc = data['response']&.first['periods']&.first['tempC']
    @winddir = data['response']&.first['periods']&.first['windDir']
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def index
    @races = Race.all
    @game = Game.new
  end

  def coordinates
    @race = Race.find(params[:id])
    render json: @race.coordinates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/rotation_helper.rb
module RotationHelper

  def boat_direction_to_angle(boat_dir, wind_dir)
    case boat_dir
    when 1
      alphaBoat = wind_dir + 45 + 0
    when 2
      alphaBoat = wind_dir + 45 + 44
    when 3
      alphaBoat = wind_dir + 45 + 59
    when 4
      alphaBoat = wind_dir + 45 + 90
    when 5
      alphaBoat = wind_dir + 45 + 133
    when 6
      alphaBoat = wind_dir + 45 + 178
    when 7
      alphaBoat = wind_dir + 45 + 225
    when 8
      alphaBoat = wind_dir + 45 + 268
    when 9
      alphaBoat = wind_dir + 45 + 300
    when 10
      alphaBoat = wind_dir + 45 + 315
    end
    return "rotate(#{alphaBoat}deg)"
  end

end

app/views/boats/_label.html.erb
<% if item == "Poppy" %>
  <div class="">
    <%= item %>
  </div>
<% elsif item == "Lemon" %>
  <div class="">
    <%= item %>
  </div>
<% else item == "Navy" %>
  <div class="">
    <%= item %>
  </div>
<% end %>

app/views/boats/new.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

<div class="">
  <div class="card-beige">
    <div class="d-flex justify-content-between">
      <div>
        <%= link_to root_path do %>
          <svg class="btn-retour" xmlns="http://www.w3.org/2000/svg" width="62" height="62" viewBox="0 0 62 62" fill="none">
            <rect width="62" height="62" rx="10" fill="#E29578"/>
            <path d="M14.7282 31.522C13.4894 30.7385 13.4862 28.9327 14.7223 28.1449L36.7915 14.0814C38.1216 13.2338 39.8636 14.1874 39.8663 15.7646L39.9151 43.8149C39.9178 45.3921 38.1791 46.3517 36.8461 45.5087L14.7282 31.522Z" fill="white"/>
          </svg>
        <% end %>
      </div>

      <div class="banner-titre text-align-center">
          <h2 class="">Pimp your boat</h2>
      </div>

      <div class="">
        <img class="avatar-bordered" alt="avatar-bordered" src="https://avatars.githubusercontent.com/u/122464388?v=4" />
      </div>
    </div>
        <div class="d-flex boat-picture" data-controller="boat-select">
          <img data-boat-select-target="img", style="height: 450px", src="https://res.cloudinary.com/dwclozjta/image/upload/v1678372133/bateau_poppy_kqqsnl.png" alt="">
          <div class="card-pimp mt-">
            <%= simple_form_for [@race, @boat] do |f| %>
              <%= f.input :name, input_html: { class: "name-boat" } , placeholder: "Name your boat"%>

              <%= f.input :color, collection: ['Poppy', 'Lemon', 'Navy'],
                          as: :radio_buttons, label_method: lambda { |item| render "label", item: item },
                          input_html: { data: { action: "change->boat-select#update" } } %>

              <%= f.submit :Start, class: "btn btn-primary btn-form" %>
            <% end %>
          </div>
        </div>
  </div>
</div>

app/views/boats/update.html.erb
<h1>Boats#update</h1>
<p>Find me in app/views/boats/update.html.erb</p>

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stormy Crossing</title>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.13.0/mapbox-gl.js"></script>
    <script src='https://npmcdn.com/@turf/turf/turf.min.js'></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display:ital@0;1&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <script defer src="https://cdn.aerisapi.com/sdk/js/mapsgl/latest/aerisweather.mapsgl.js"></script>
    <link href="https://cdn.aerisapi.com/sdk/js/mapsgl/latest/aerisweather.mapsgl.css" rel="stylesheet" />
  </head>

  <body>
    <%# <%= render "shared/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<%= @wind_speedy %>
<%= @wind_direction %>


<div class="banner" style="background-image: url('https://res.cloudinary.com/dwclozjta/image/upload/v1678380009/Map-banner-min-ok_bc7wrs.png');">
  <div class="container text-center">
  <div class="">
   <h1 class="main-title">STORMY <br> CROSSING</h1>
   <p style="text-align:center; color:white; font-size:20px"><em>Race to the horizon</em></p>
  </div>
   <img src="https://res.cloudinary.com/dwclozjta/image/upload/v1678881235/pngegg_2_qlwdll.png" style="position:absolute; top:10px; right:0; z-index:6;" alt="">
   <img src="https://res.cloudinary.com/dwclozjta/image/upload/v1678378027/arrow2_wqbyvc.png" alt="arrow" class="arrow">
    <%= link_to "Discover", races_path, :class=>"btn btn-primary main-btn" %>

    <img class="boat" src="https://res.cloudinary.com/dwclozjta/image/upload/v1678282159/kisspng-sail-2016-17-es-vende-globe-france-imoca-60-boat-jules-rimet-trophy-5b5151faba80b2.9826272515320560587639_xuug15.png" alt="boat">

  </div>

</div>
<div style="background-color:#ECE9D5" class="wave2" style=""></div>

<div class="section-2">
  <img src="https://res.cloudinary.com/dwclozjta/image/upload/v1678291442/gouvernail_hagrb6.png" alt="gouvernail" class="gouvernail">
  <div class="container py-4">
    <h1>About Us</h1>
    <br>
    <p class="description_home">
    Our passion for the open seas and the art of sailing is what drives us to create the most realistic and immersive sailing experiences possible.
    <br>
    <br>
    <br>
    Our team of experienced game developers and sailing enthusiasts work tirelessly to create games that are both entertaining and educational, providing players with a truly authentic sailing experience.
    <br>
    <br>
    <br>
    With a focus on realism, we have developed cutting-edge technology that accurately simulates the physics of sailing, allowing players to experience the challenges and exhilaration of racing a sailboat through different weather conditions, ocean currents, and wind patterns.
    </p>
    <br>
    <br>
    <div class="ourrace" style="position:relative">
      <img src="https://res.cloudinary.com/dwclozjta/image/upload/v1678293637/surligner_gqcoti.png" alt="underline" class="underline">
      <h1 style="text-align:right;position:relative">Our Races</h1>
    </div>
  </div>

 <div class="cards container py-4">

  <div class="card-trip effet">
    <img src="https://res.cloudinary.com/dwclozjta/image/upload/v1678377650/south_america_wzbmjx.jpg" />
    <div class="card-trip-infos">
        <h2>South America</h2>
        <br>
        <p>Come face will the tumultuous waters of the Indian Ocean, facing strong winds and ocean currents.</p>
        <br>
    </div>
  </div>
  <div class="card-trip effet">
    <img src="https://res.cloudinary.com/dwclozjta/image/upload/v1678377639/Africa_zd8rm1.jpg" />
    <div class="card-trip-infos">
        <h2>South Africa</h2>
        <br>
        <p>Embark on an exciting nautical adventure that spans over 10,000 kilometers across the Atlantic Ocean." </p>
        <br>
    </div>
  </div>
  <div class="card-trip effet">
    <img src="https://res.cloudinary.com/dwclozjta/image/upload/v1678377639/Africa_zd8rm1.jpg" />
    <div class="card-trip-infos">
        <h2>East Africa</h2>
        <br>
        <p>Navigate strategically to reach the finish line first and become the winner of this iconic race.</p>
        <br>
  </div>
</div>

app/views/races/index.html.erb
<div class="section-races" style="background-color:#ECE9D5;">

      <div class="d-flex justify-content-between " style="padding-top:20px; padding-bottom:20px;padding-left: 40px;padding-right: 40px;">
          <div>
              <%= link_to root_path do %>
                <svg class="btn-retour" xmlns="http://www.w3.org/2000/svg" width="62" height="62" viewBox="0 0 62 62" fill="none">
                    <rect width="62" height="62" rx="10" fill="#E29578"/>
                    <path d="M14.7282 31.522C13.4894 30.7385 13.4862 28.9327 14.7223 28.1449L36.7915 14.0814C38.1216 13.2338 39.8636 14.1874 39.8663 15.7646L39.9151 43.8149C39.9178 45.3921 38.1791 46.3517 36.8461 45.5087L14.7282 31.522Z" fill="white"/>
                </svg>
              <%end %>
          </div>
          <div class="banner-titre text-align-center">
              <h2 class="">Select your race</h2>
          </div>
          <div class="">
              <img class="avatar-bordered" alt="avatar-bordered" src="https://avatars.githubusercontent.com/u/122464388?v=4" />
          </div>
      </div>
      <div class="container">
        <div class="d-flex justify-content-between race-selector" data-controller="map" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" data-map-client-id-value="<%= ENV["CLIENT_ID"] %>" data-map-client-secret-value="<%= ENV["CLIENT_SECRET"] %>">
          <div class="card-scrolling">
              <% @races.each do |race| %>
                <div class="card-scroll">
                    <div class="">
                        <%= link_to new_race_boat_path(race), class:"text-decoration-none", data: { action: "mouseenter->map#draw_animated_line mouseleave->map#clearIntervalle", map_race_id_param: { race_id: race.id }} do %>
                          <div class="front-face">
                              <div class="card-category effet" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= race.photo %>)">
                                  <%= race.name %>
                              </div>
                          </div>
                        <% end %>
                    </div>
                </div>
              <% end %>
          </div>
          <div id="map" data-map-target="map" style="width: 100%; height: 600px; padding-top: 9px;">
          </div>
        </div>
    </div>
  </div>
</div>